#!/usr/bin/perl

 use HTTP::Proxy;
 use HTTP::Recorder;

 my $proxy = HTTP::Proxy->new( port => 3128 );

 # create a new HTTP::Recorder object
 my $agent = new HTTP::Recorder;

 # set the log file (optional)
 $agent->file("/home/joerg/httpdump");

 # set HTTP::Recorder as the agent for the proxy
 $proxy->agent( $agent );

 # start the proxy
 $proxy->start();

 1;

